# Generated by Django 5.1.2 on 2024-12-19 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_doctor_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
    ]
