# Generated by Django 5.1.2 on 2024-12-20 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_remove_message_appointment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment'),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
